services:
  - type: web
    name: uno-websocket
    runtime: go
    rootDir: apps/server
    buildCommand: go build -o main
    startCommand: ./main
    envVars:
      - key: PORT
        sync: false
